config/routes.rb
Rails.application.routes.draw do
  resources :purchases, only: :create
  resources :buildings, only: [:new, :create, :index]
  root 'buildings#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
    validates :owner, presence: true, uniqueness: true
    # validates :owner, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :price, presence: true
    enum subclass: [:house, :complex_building, :commercial_unit]
    has_one_attached :image
end

app/models/commercial_unit.rb
class CommercialUnit < Building
    validates :shops, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :sqmt, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :parking, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :address, presence: true
end

app/models/complex_building.rb
class ComplexBuilding < Building
    validates :units, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :sqmt, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :address, presence: true
end

app/models/house.rb
class House < Building
    validates :rooms, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :sqmt, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :floors, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
    validates :air_cond, presence: true
    validates :address, presence: true

end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :building
  validates :user, presence: true
  validates :user, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    if params["building"]["subclass"] == "house"
      @building = House.new(building_params)
    elsif params["building"]["subclass"] == "complex_building"
      @building = ComplexBuilding.new(building_params)
    else
      @building = CommercialUnit.new(building_params)
    end
    if @building.save
      flash[:success] = "Building created"
      redirect_to root_url  
    else
      flash[:error] = "Error. Please try again. Fill out form completely with correct email"
      redirect_to new_building_path
    end
  end

  def index
    @buildings = Building.all.order("created_at DESC")
  end

  def new
    @building = Building.new
  end

  private 

  def building_params
    params.require(:building).permit(:owner, :address, :rooms, :sqmt, :floors, :air_cond, :price, :units, :shops, :parking, :subclass, :image)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @user = params[:email]
    @building = Building.find(params[:building_id])
    @purchase = Purchase.new(user: @user, building: @building)
    
      if @purchase.save
        VeryLongTaskJob.perform_later(user: @user, building_id: @building.id)
        flash[:success] = "Purchase succesful. Check your email."
        redirect_to root_url      
      else
        flash[:error] = "Error, please try again. Ensure email is correct"
        redirect_to root_url
      end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/buildings/index.html.erb
<div class="container pt-5">
    <h2>All Assets</h2>
    <div class="row pt-5">

        <% @buildings.each do |building| %>
        <div class="col col-xs-12 col-md-6 col-lg-4 p-2">

            <div class="card" style="width: 18rem;">
                <% if building.image.attached? %>
                    <%= image_tag building.image.variant(resize_to_limit: [100, 100]), class: "card-img-top" %>
                <% end %>

                <div class="card-body">
                    <h5 class="card-title"><%= building.address %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= building.subclass %></h6>
                    <p class="card-text"><%= building.sqmt %> square meters</p>
                    <% if building.subclass == "house" %>

                    <p class="card-text"><%= building.rooms %> rooms</p>
                    <p class="card-text"><%= building.floors %> floors</p>
                    <% if building.air_cond %>
                    <p class="card-text">Air Conditioning</p>
                    <% else %>
                    <p class="card-text">No Air Conditioning</p>
                    <% end %>


                    <% elsif building.subclass == "complex_building" %>

                    <p class="card-text"><%= building.units %> units</p>

                    <% elsif building.subclass == "commercial_unit" %>

                    <p class="card-text"><%= building.shops %> shops</p>
                    <p class="card-text"><%= building.parking %> parking</p>

                    <% end %>

                    <p class="card-text">Price: <%= building.price %></p>

                    <%= form_with(url: purchases_path, method: :create, html: {class: "form-horizontal", role: "form"}, local: true) do |f| %>
                        <div class="form-group" id="owner-asset-form">
                            <%= f.label "email" %>
                            <%= f.text_field :email %>
                            <%= f.hidden_field :building_id, :value => building.id %>
                        </div>
                        <div class="form-group">
                            <%= f.submit 'Make a Purchase', class: "btn btn-primary" %> 
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/buildings/new.html.erb
<div class="container pt-5">
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col-8 d-flex justify-content-center">
            <%= form_with(model: @building, method: :create, html: {class: "form-horizontal", role: "form"}, local: true) do |f| %>
                <div class="form-group form-inline pb-3" id="subclass-asset-form">
                    <%= f.label "subclass" %>
                    <%= f.select :subclass, Building.subclasses.keys, include_blank: true, :html => {:class => "form-control"} %>
                </div>
                <div class="form-group" id="owner-asset-form">
                    <%= f.label "owner" %>
                    <%= f.text_field :owner %>
                </div>
                <div class="form-group" id="address-asset-form">
                    <%= f.label "address" %>
                    <%= f.text_field :address %>
                </div>
                <div class="form-group" id="price-asset-form">
                    <%= f.label "price" %>
                    <%= f.number_field :price, step: :any%>
                </div>
                <div class="form-group" id="sqmt-asset-form">
                    <%= f.label "sqmt" %>
                    <%= f.number_field :sqmt %>
                </div>
                <div class="form-group" id="rooms-asset-form" style="display: none" disabled>
                    <%= f.label "rooms" %>
                    <%= f.number_field :rooms %>
                </div>
                <div class="form-group" id="floors-asset-form" style="display: none" disabled>
                    <%= f.label "floors" %>
                    <%= f.number_field :floors %>
                </div>
                <div class="form-group" id="aircon-asset-form" style="display: none" disabled>
                    <%= f.label "air conditioning" %>
                    <%= f.check_box :air_cond %>
                </div>
                
                <div class="form-group" id="units-asset-form" style="display: none" disabled>
                    <%= f.label "units" %>
                    <%= f.number_field :units %>
                </div>
                <div class="form-group" id="shops-asset-form" style="display: none" disabled>
                    <%= f.label "shops" %>
                    <%= f.number_field :shops %>
                </div>
                <div class="form-group" id="parking-asset-form" style="display: none" disabled>
                    <%= f.label "parking" %>
                    <%= f.number_field :parking%>
                </div>
                <div class="form-group">
                    <%= f.file_field :image %>
                </div>
                <div class="form-group">
                    <%= f.submit 'Add Building', class: "btn btn-primary"  %> 
                </div>
            <% end %>
        </div>
        <div class="col-2">
        </div>
    </div>
</div>

<div>

<script>
$('select').on('change', function() {
  if (this.value == "house"){

  $('#rooms-asset-form').show()
  $('#floors-asset-form').show()
  $('#aircon-asset-form').show()
  $('#units-asset-form').hide()
  $('#units-asset-form').prop('disabled', true);
  $('#shops-asset-form').hide()
  $('#shops-asset-form').prop('disabled', true);
  $('#parking-asset-form').hide()
  $('#parking-asset-form').prop('disabled', true);

  }
   
  else if (this.value == "complex_building"){

  $('#rooms-asset-form').hide()
  $('#rooms-asset-form').prop('disabled', true);
  $('#floors-asset-form').hide()
  $('#floors-asset-form').prop('disabled', true);
  $('#aircon-asset-form').hide()
  $('#aircon-asset-form').prop('disabled', true);
  $('#units-asset-form').show()
  $('#shops-asset-form').hide()
  $('#shops-asset-form').prop('disabled', true);
  $('#parking-asset-form').hide()
  $('#parking-asset-form').prop('disabled', true);

  }
    
  else if (this.value == "commercial_unit"){

  $('#rooms-asset-form').hide()
  $('#rooms-asset-form').prop('disabled', true);
  $('#floors-asset-form').hide()
  $('#floors-asset-form').prop('disabled', true);
  $('#aircon-asset-form').hide()
  $('#aircon-asset-form').prop('disabled', true);
  $('#units-asset-form').hide()
  $('#units-asset-form').prop('disabled', true);
  $('#shops-asset-form').show()
  $('#parking-asset-form').show()

  }
    
  

});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SrlTestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="initial-scale=1">
  </head>

  <body>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <% flash.each do |type, msg| %>
      <% if type == "success" %>
        <div class="alert alert-success mb-0">
          <%= msg %>
        </div>
      <% else %>
        <div class="alert alert-danger mb-0">
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <nav class="navbar navbar-light bg-light">
      <a class="nav-link" href="/">Home</a>
      <a class="nav-link" href="/buildings/new">Add New Asset</a>
    </nav>
    <%= yield %>

  </body>
</html>